version: "3.7"
services:
  dev:
    build:
      context: .
      args:
        - PYTHON_ENV=development
    environment:
      - APP_NAME=phonebook-service
    volumes:
      - "./reports:/app/reports"
    depends_on:
      - db
    links:
      - "db"
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=phonebook
      - POSTGRES_USER=phonebook
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./postgres-data:/var/lib/postgresql/data