test_name: Test phonebook service

includes:
  - !include common.yaml

  
stages:
  - name: Make sure we can create new contact
    request:
     url: "{url:s}"
     method: POST
     json:
      username: testUser
      first_name: first
      last_name: last
      email: test@email.com
      password: "123456"
      phone: "111111"
    response:
     status_code: 200
     headers:
      content-type: application/json
     save:
      body:
        contact_id: id
  - name: Make sure we can find contact by email
    request:
      url: "{url:s}/findByEmail?email=test@email.com"
      method: GET
    response:
      status_code: 200
  - name: Make sure we can find contact by username
    request:
      url: "{url:s}/findByName?name=testUser"
      method: GET
    response:
      status_code: 200
  - name: Make sure we can find contact by ID
    request:
      url: "{url:s}/{contact_id:d}"
      method: GET
    response:
      status_code: 200
  - name: Make sure we can update a contact
    request:
      url: "{url:s}/{contact_id:d}"
      method: PUT
      json:
        phone: "222222"
    response:
      status_code: 200
  - name: Make sure we can delete a contact
    request:
      url: "{url:s}/{contact_id:d}"
      method: DELETE
    response:
      status_code: 200
  - name: Make sure we can't delete non existed contact
    request:
      url: "{url:s}/9999"
      method: DELETE
    response:
      status_code: 404
  - name: Make sure we can't update a non existed contact
    request:
      url: "{url:s}/9999"
      method: PUT
      json:
        phone: '111111'
    response:
      status_code: 404